name: LHCI-upload-to-private-server
on: push
jobs:
  # TODO(exterkamp): delete this from this repo ;)
  populate-ci-server-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on urls and upload data to private lhci server
        uses: ./
        with:
          lhci_server: ${{ secrets.LHCI_SERVER }}
          api_token: ${{ secrets.LHCI_API_TOKEN }}
          urls: 'https://exterkamp.codes/'
