name: LHCI-assert-on-lighthouserc
on: push
jobs:
  # This pass/fails a build with LHCI assertions via an rc-file.
  assert-on-lighthouserc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: ./
        with:
          urls: 'https://exterkamp.codes/'
          configPath: '.github/lighthouse/lighthouserc_assertions.json'