name: Run action locally
on: push
jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload to public-repo
        uses: ./
        with:
          urls: |
            https://exterkamp.codes/
            https://google.com/
          runs: 1
      - name: Save artifacts
        uses: actions/upload-artifact@v1
        with:
          name: public-repo-artifacts
          path: '.lighthouseci'
      - name: Upload to secret-server with secret key
        uses: ./
        with:
          lhci_server: ${{ secrets.LHCI_SERVER }}
          api_token: ${{ secrets.LHCI_API_TOKEN }}
          url: 'https://exterkamp.codes/'
          runs: 1
      - name: Save artifacts
        uses: actions/upload-artifact@v1
        with:
          name: private-lhci-artifacts
          path: '.lighthouseci'
      - name: Assert on a budget
        uses: ./
        with:
          url: 'https://exterkamp.codes/'
          budget_path: '.github/lighthouse/budget.json'
          runs: 1
      - name: Assert on a assertions from rc-file
        uses: ./
        with:
          url: 'https://exterkamp.codes/'
          rc_file: '.github/lighthouse/rc_file_assertions_only.json'
          runs: 1
      - name: Use rc-file for Chrome flags and config
        uses: ./
        with:
          url: 'https://exterkamp.codes/'
          rc_file: '.github/lighthouse/rc_file_collection_only.json'
          runs: 1
