name: Run action locally
on: push
jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload to public-repo
        uses: ./
        with:
          urls: |
            https://exterkamp.codes/
            https://google.com/
          runs: 1
      - name: Upload to secret-server with secret key
        uses: ./
        with:
          lhci_server: ${{ secrets.LHCI_SERVER }}
          api_token: ${{ secrets.LHCI_API_TOKEN }}
          url: 'https://exterkamp.codes/'
          runs: 1
      - name: Assert on a budget
        uses: ./
        with:
          lhci_server: ${{ secrets.LHCI_SERVER }}
          api_token: ${{ secrets.LHCI_API_TOKEN }}
          url: 'https://exterkamp.codes/'
          budgetPath: '.github/lighthouse/budget.json'
          runs: 1
