name: Run action locally
on: push
jobs:
  run-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload to public-repo
        uses: ./
        with:
          urls: |
            https://exterkamp.codes/
          extraHeaders: '{"x-github-action":"true"}'
          runs: 2
      - name: Upload to secret-server with secret key
        uses: ./
        with:
          lhci_server: ${{ secrets.LHCI_SERVER }}
          api_token: ${{ secrets.LHCI_API_TOKEN }}
          url: 'https://exterkamp.codes/'
          chromeFlags: '--window-size=1200,800'
          configPath: .github/lighthouse/desktop-config.js
          throttlingMethod: devtools
          onlyCategories: 'performance'
          runs: 3
          extraHeaders: '{"x-github-action":"true"}'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-results
          path: './.lighthouseci'
