name: Run action locally
on: push
jobs:
  # This is an advanced fully hermetic run of Lighthouse, using custom config.
  hermetic-advanced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use rc-file for Chrome flags and config
        uses: ./
        with:
          urls: 'https://alekseykulikov.com/'
          rc_file_path: '.github/lighthouse/rc_file_custom_config.json'
          runs: 1
          no_upload: true
      - name: Save artifacts
        uses: actions/upload-artifact@v1
        with:
          name: advanced-hermetic-artifacts
          path: '.lighthouseci'
  # This is a run that targets static files using static-dist-dir.
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use rc-file for Chrome flags and config
        uses: ./
        with:
          static_dist_dir: './dist'
          runs: 1
  # This is a basic Lighthouse run over multiple URLs that uses temporary-public-storage.
  multiple-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload to public-repo
        uses: ./
        with:
          urls: |
            https://alekseykulikov.com/
            https://treo.sh/
            https://google.com/
          runs: 1
  # This pass/fails a build with a budgets.json. 
  assert-on-budget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Assert on a budget
        uses: ./
        with:
          urls: 'https://alekseykulikov.com/'
          budget_path: '.github/lighthouse/passable_budget.json'
          runs: 1
  # This pass/fails a build with LHCI assertions via an rc-file.
  assert-on-rc-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Assert on assertions from rc-file
        uses: ./
        with:
          urls: 'https://exterkamp.codes/'
          rc_file_path: '.github/lighthouse/rc_file_assertions.json'
          runs: 1
  # TODO(exterkamp): delete this from this repo ;)
  populate-ci-server-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload to secret-server with secret key
        uses: ./
        with:
          lhci_server: ${{ secrets.LHCI_SERVER }}
          api_token: ${{ secrets.LHCI_API_TOKEN }}
          urls: 'https://exterkamp.codes/'
